export const TravelCategory = [
  "Any",
  "Tours",
  "Flights",
  "Hotels",
  "Cruises",
  "Car_Rentals",
  "Travel_Insurance",
  "Visa_Services",
  "Adventure_Travel",
  "Honeymoon_Packages",
  "Group_Travel",
  "Custom_Packages",
];

export const TravelDestinations = [
  "Paris, France",
  "Kyoto, Japan",
  "Rome, Italy",
  "Cape Town, South Africa",
  "Santorini, Greece",
  "New York City, USA",
  "Machu Picchu, Peru",
  "Venice, Italy",
  "Bora Bora, French Polynesia",
  "Dubai, UAE",
  "Barcelona, Spain",
  "Sydney, Australia",
  "Istanbul, Turkey",
  "Rio de Janeiro, Brazil",
  "Prague, Czech Republic",
  "Amsterdam, Netherlands",
  "Reykjavik, Iceland",
  "Bangkok, Thailand",
  "Zurich, Switzerland",
  "Marrakech, Morocco",
];
